name: Build and test on Feature Branches

on:
  push:
    branches: [ "feature/**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3  
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    - run: pwd & ls -al

    - run: mvn -B package --file BackEnd/pom.xml